# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC

# Trigger the workflow on every push to any branch
on: 
  push:
    branches:
      - main  # Customize this to your default branch if different
  workflow_dispatch: 

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Allows access to repository contents

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to Azure using OIDC
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}      # App Registration's Client ID
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}      # Azure Active Directory Tenant ID
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Azure Subscription ID
          enable-AzPSSession: true  # Enable Azure PowerShell session

      # Step 3: Run Azure CLI commands
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Showing Azure Account Details"
            az account show

      # Step 4: Run Azure PowerShell commands
      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Write-Host "Showing Azure Context Details"
            Get-AzContext
